name: pocket-js-server
services:
  db:
    container_name: db
    image: bitnami/postgresql:13.16.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - 3333:3333
    depends_on:
      - db